@startuml
set separator none
title Medistock E-Commerce - Containers

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

System(SistemasERPClínicas, "Sistemas ERP (Clínicas)", $descr="Sistema externo que consume la API para abastecimiento automatizado.", $tags="", $link="")
System(PasareladePagos, "Pasarela de Pagos", $descr="Procesa pagos (Webpay/MercadoPago).", $tags="", $link="")
System(APIdeLogística, "API de Logística", $descr="Genera tracking de despachos (Shippo/Mock).", $tags="", $link="")

System_Boundary("MedistockECommerce_boundary", "Medistock E-Commerce", $tags="") {
  Container(MedistockECommerce.APIRESTfulFastAPI, "API RESTful (FastAPI)", $techn="Python/FastAPI", $descr="Provee servicios de catálogo, inventario y órdenes", $tags="", $link="")
  Container(MedistockECommerce.BasedeDatos, "Base de Datos", $techn="PostgreSQL", $descr="Almacena información de productos, inventario, usuarios y órdenes", $tags="", $link="")
  Container(MedistockECommerce.VolumendeDatos, "Volumen de Datos", $techn="Docker Volume (pg_data)", $descr="Persistencia física de la base de datos", $tags="", $link="")
}

Rel(SistemasERPClínicas, MedistockECommerce.APIRESTfulFastAPI, "Consume catálogo y stock", $techn="REST/HTTPS", $tags="", $link="")
Rel(MedistockECommerce.APIRESTfulFastAPI, PasareladePagos, "Inicia pagos", $techn="REST/HTTPS", $tags="", $link="")
Rel(MedistockECommerce.APIRESTfulFastAPI, APIdeLogística, "Solicita tracking", $techn="REST/HTTPS", $tags="", $link="")
Rel(MedistockECommerce.APIRESTfulFastAPI, MedistockECommerce.BasedeDatos, "Lee de y escribe en", $techn="SQL/AsyncPG", $tags="", $link="")
Rel(MedistockECommerce.BasedeDatos, MedistockECommerce.VolumendeDatos, "Almacena datos en", $techn="I/O", $tags="", $link="")

SHOW_LEGEND(true)
@enduml