@startuml
set separator none
title Medistock E-Commerce - System Context

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>

Person(InstituciónClínica, "Institución (Clínica)", $descr="Compra insumos médicos al por mayor.", $tags="", $link="")
System(SistemasERPClínicas, "Sistemas ERP (Clínicas)", $descr="Sistema externo que consume la API para abastecimiento automatizado.", $tags="", $link="")
System(PasareladePagos, "Pasarela de Pagos", $descr="Procesa pagos (Webpay/MercadoPago).", $tags="", $link="")
System(APIdeDivisas, "API de Divisas", $descr="Convierte moneda en tiempo real.", $tags="", $link="")
Person(Paciente, "Paciente", $descr="Compra insumos médicos (B2C).", $tags="", $link="")
System(MedistockECommerce, "Medistock E-Commerce", $descr="Plataforma centralizada para venta y distribución de insumos.", $tags="", $link="")

Rel(InstituciónClínica, MedistockECommerce, "Realiza pedidos institucionales", $techn="", $tags="", $link="")
Rel(Paciente, MedistockECommerce, "Realiza compras particulares", $techn="", $tags="", $link="")
Rel(SistemasERPClínicas, MedistockECommerce, "Consume catálogo y stock", $techn="REST/HTTPS", $tags="", $link="")
Rel(MedistockECommerce, PasareladePagos, "Inicia y valida pagos", $techn="REST/HTTPS", $tags="", $link="")
Rel(MedistockECommerce, APIdeDivisas, "Solicita conversión", $techn="REST/HTTPS", $tags="", $link="")

SHOW_LEGEND(true)
@enduml